import { CategoryProvider } from "@/context/CategoryContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CategoryProvider>
        <body>{children}</body>
      </CategoryProvider>
    </html>
  );
}
