import type { Metadata } from "next";
import { FilterProvider } from "@/context/FilterContext";
import QueryProvider from "@/context/QueryProvider";
import { SelectedProvider } from "@/context/SelectedContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <FilterProvider>
          <SelectedProvider>
            <body>{children}</body>
          </SelectedProvider>
        </FilterProvider>
      </QueryProvider>
    </html>
  );
}
